# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-09 11:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('满意', '满意'), ('一般', '一般'), ('不满意', '不满意')], default='满意', max_length=10, verbose_name='服务评价')),
                ('remarks', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '服务评价',
                'verbose_name_plural': '服务评价',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10, verbose_name='预约部门')),
                ('applicant', models.CharField(max_length=10, verbose_name='预约者')),
                ('date', models.DateField(default='2018-07-09', verbose_name='预约日期')),
                ('field', models.CharField(choices=[('9:00 - 12:00', '9:00 - 12:00'), ('14:00 - 17:00', '14:00 - 17:00')], default='9:00 - 12:00', max_length=30, verbose_name='场次')),
                ('type', models.CharField(choices=[('待审核', '待审核'), ('已预约', '已预约'), ('已完成', '已完成')], default='待审核', max_length=10, verbose_name='场次状态')),
                ('client_name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('client_level', models.CharField(max_length=10, verbose_name='客户级别')),
                ('mobile', models.CharField(max_length=20, verbose_name='预约者联系方式')),
                ('remarks', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '展厅场次',
                'verbose_name_plural': '展厅场次',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Reservation', verbose_name='预约记录'),
        ),
    ]
