# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='department',
            field=models.CharField(max_length=20, verbose_name='预约部门'),
        ),
    ]
